export const MockProducts= [
        { 
            id: 1, 
            name: 'Fresh Peach', 
            category: 'Vegetables', 
            price: 32, 
            oldPrice: 45, 
            image: '/Banner.jpg', 
            brand: 'Brand A', 
            productType: 'Fresh', 
            availableProduct: 'In Stock', 
            image2: '/Banner.jpg', 
            image3: '/Banner.jpg',
            description: 'Super fresh and flavorful- arrived perfectly nice.',
            rating: 3.8,
            measure: 'kg',
            priceForoneKilo: 45,
            NutritionalFacts: [{ id: 1, name: 'calories', value: '45' }],
            quantity :1 
        },
        { 
            id: 2, 
            name: 'Organic Pineapple', 
            category: 'Fruits', 
            price: 45, 
            oldPrice: 60, 
            image: '/Banner.jpg', 
            brand: 'Brand B', 
            productType: 'Organic', 
            availableProduct: 'Out of Stock', 
            image2: '/Banner.jpg', 
            image3: '/Banner.jpg',
            description: 'Sweet and juicy, very sweet and clean.',
            rating: 4.2, 
            measure: 'kg',
            priceForoneKilo: 35,
            NutritionalFacts: [{ id: 2, name: 'calories', value: '45' }],
            quantity :10
        },
        { 
            id: 3, 
            name: 'Fresh Broccoli', 
            category: 'Vegetables', 
            price: 20, 
            oldPrice: 30, 
            image: '/Banner.jpg', 
            brand: 'Brand C', 
            productType: 'Frozen', 
            availableProduct: 'In Stock', 
            image2: '/Banner.jpg', 
            image3: '/Banner.jpg',
            description: 'Consistent quality every time, highly recommend.',
            rating: 4.0,
            measure: 'kg',
            priceForoneKilo: 35,
            NutritionalFacts: [{ id: 3, name: 'calories', value: '45' }],
            quantity :5
        },
        { 
            id: 4, 
            name: 'Fresh Milk', 
            category: 'Dairy', 
            price: 15, 
            oldPrice: 22, 
            image: '/Banner.jpg', 
            brand: 'Brand A', 
            productType: 'Fresh', 
            availableProduct: 'Out of Stock', 
            image2: '/Banner.jpg', 
            image3: '/Banner.jpg',
            description: 'Pure and fresh daily dairy product.',
            rating: 4.5,
            measure: 'kg',
            priceForoneKilo: 35,
            NutritionalFacts: [{ id: 4, name: 'calories', value: '45' }],
            quantity :21
        },
    ];
